version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samdeploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10oknv41nby5q"
s3_prefix = "samdeploy"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
