AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  javahome-app
  Sample SAM Template for javahome-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Tracing: Active

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  SAMLogs:
    Type: AWS::Logs::LogGroup
  
  ValidationStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Type: EXPRESS
      DefinitionUri: statemachine/stateMachine.asl.json
      DefinitionSubstitutions:
        HelloFromLocalStepFunctionArn: !GetAtt HelloFromLocalStepFunction.Arn
      Events:
        ValidationApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /hello
            RestApiId: MyApi

      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt SAMLogs.Arn
        IncludeExecutionData: true
        Level: ALL
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref HelloFromLocalStepFunction
        - CloudWatchLogsFullAccess

  HelloFromLocalStepFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/HelloSF/
      Handler: helloWorld.lambda_handler
      Runtime: python3.9

Outputs:
  ValidationStateMachineArn:
    Description: "fdf"
    Value: !Ref ValidationStateMachine
  HelloAPIUrl:
    Description: "Gateway Http API URL"
    Value: !Sub https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/
  